def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]
pipeline {
    agent any

    environment {
        registryCredential = 'ecr:us-east-1:awscred'
        appRegistry = '380907317030.dkr.ecr.us-east-1.amazonaws.com/vprofile'
        vprofileRegistry = 'https://380907317030.dkr.ecr.us-east-1.amazonaws.com'
        cluster = 'vproprod'
        service = 'vproprod'
    }
    stages {
        stage ('Deploy to Prod ECS'){
            steps{
                withAWS(credentials: 'awscred', region: 'us-east-1'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
     post {
        always {
            echo 'Slack notifications - test'
            slackSend channel: '#jenkinscicd',
             color: COLOR_MAP[currentBuild.currentResult],
             message: "*$currentBuild.currentResult:* Job $env.JOB_NAME build $env.BUILD_NUMBER More at: $env.BUILD_URL \n"
        }
    }
}